mt.exe -tlb:COMDLG32.OCX		-dll:COMDLG32.OCX	-out:COMDLG32.OCX.manifest
mt.exe -tlb:mscomctl.ocx		-dll:mscomctl.ocx	-out:mscomctl.OCX.manifest
mt.exe -tlb:richtx32.ocx		-dll:richtx32.ocx	-out:richtx32.OCX.manifest
mt.exe -tlb:comct332.ocx		-dll:comct332.ocx	-out:comct332.OCX.manifest
mt.exe -tlb:picclp32.ocx		-dll:picclp32.ocx	-out:picclp32.OCX.manifest
mt.exe -tlb:msdatgrd.ocx		-dll:msdatgrd.ocx	-out:msdatgrd.OCX.manifest
mt.exe -tlb:msmask32.ocx		-dll:msmask32.ocx	-out:msmask32.OCX.manifest
mt.exe -tlb:MSADODC.OCX		-dll:MSADODC.OCX	-out:MSADODC.OCX.manifest
mt.exe -tlb:tabctl32.ocx		-dll:tabctl32.ocx	-out:tabctl32.OCX.manifest
mt.exe -tlb:msdatlst.ocx		-dll:msdatlst.ocx	-out:msdatlst.OCX.manifest
mt.exe -tlb:mscomct2.ocx		-dll:mscomct2.ocx	-out:mscomct2.OCX.manifest
mt.exe -tlb:mshflxgd.ocx		-dll:mshflxgd.ocx	-out:mshflxgd.OCX.manifest
mt.exe -tlb:GRAPH32.OCX		-dll:GRAPH32.OCX	-out:GRAPH32.OCX.manifest
mt.exe -tlb:AppOcxClient.ocx		-dll:AppOcxClient.ocx	-out:AppOcxClient.OCX.manifest
mt.exe -tlb:todg8.ocx		-dll:todg8.ocx	-out:todg8.OCX.manifest
mt.exe -tlb:c1sizer.ocx		-dll:c1sizer.ocx	-out:c1sizer.OCX.manifest
mt.exe -tlb:vsflex8l.ocx		-dll:vsflex8l.ocx	-out:vsflex8l.OCX.manifest
mt.exe -tlb:vsflex8l.ocx		-dll:vsflex8l.ocx	-out:vsflex8l.OCX.manifest
mt.exe -tlb:c1sizer.ocx		-dll:c1sizer.ocx	-out:c1sizer.OCX.manifest
mt.exe -tlb:c1awk.ocx		-dll:c1awk.ocx	-out:c1awk.OCX.manifest
mt.exe -tlb:tizonex8.dll		-dll:tizonex8.dll	-out:tizonex8.dll.manifest
mt.exe -tlb:truedc8.ocx		-dll:truedc8.ocx	-out:truedc8.OCX.manifest
mt.exe -tlb:vsflex8d.ocx		-dll:vsflex8d.ocx	-out:vsflex8d.OCX.manifest
mt.exe -tlb:vsflex8n.ocx		-dll:vsflex8n.ocx	-out:vsflex8n.OCX.manifest
mt.exe -tlb:vsstr8.ocx		-dll:vsstr8.ocx	-out:vsstr8.OCX.manifest
mt.exe -tlb:vspdf8.ocx		-dll:vspdf8.ocx	-out:vspdf8.OCX.manifest
mt.exe -tlb:vsflex8.ocx  		-dll:vsflex8.ocx  	-out:vsflex8.ocx.manifest
mt.exe -tlb:MSBIND.DLL		-dll:MSBIND.DLL	-out:MSBIND.DLL.manifest
mt.exe -tlb:MSDBRPTR.DLL		-dll:MSDBRPTR.DLL	-out:MSDBRPTR.DLL.manifest
mt.exe -tlb:msstdfmt.dll		-dll:msstdfmt.dll	-out:msstdfmt.dll.manifest
mt.exe -tlb:dx7vb.dll		-dll:dx7vb.dll	-out:dx7vb.dll.manifest
